# <font color=blue>Assignments for "basics of NumPy Array"</font>

1. Create 3 lists representing house features, each list containing 10 values. First one for squaremeter of house, second one for rooms and last one for price. Then, create an array combining these lists.

In [ ]:
import numpy as np
sqm = [150,160,170,180,190,200,210,220,230,240]
num_o_rooms =[5,6,7,8,9,10,11,12,13,14]
price =[300000,350000,400000,450000,500000,550000,600000,650000,700000,750000]

feat_house =np.array([sqm,num_o_rooms,price])

print(feat_house)



2. Transpose the array you have created, so that every line can represent features of one house.

In [ ]:
feat_each_house= np.transpose(feat_house)
print(feat_each_house)

3. Display the shape of the array and explain what it means.

In [ ]:
x,y = feat_each_house.shape
print("{} : # of rows and {} :# of columns".format(x,y))
print("{} rows represent each of the houses ".format(x))
print("{} colums represent the features - squaremeters, # of rooms and price- of each house ".format(y))


4. Write a function that returns an array of ones with zeros where both row and column numbers are even. Sample array is below. Number of rows and columns will be entered as parameters.

```python
    shape(6 x 5) --> [[1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]
                      [1   1   1   1   1]
                      [1   0   1   0   1]]
```

In [ ]:
import numpy as np

def sample_array():
    array_ = np.ones([6,5])
    for i in np.arange(1,6,2):
        for j in np.arange(1,5,2):
              array_[i,j]=0       
    print(array_)    
    return 

sample_array()
    